name: Actualizar README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 */12 * * *"

jobs:
  Cancelacion:
    runs-on: ubuntu-latest
    steps:
    - name: Cancelar generaciones redundantes
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
  
  Generar:
    needs: [Cancelacion]
    runs-on: ubuntu-latest
    steps:
    - name: Generar el README
      uses: actions/checkout@v3
    - name: Generar github-contribution-grid-snake.svg
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    - name: push github-contribution-grid-snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
          target_branch: output
          build_dir: dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Configurar node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name nothiaki
        git config user.email celsohenrique367@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Actualizar README.md con las novedades"
        git push origin master
